# Generated by Django 3.2 on 2022-01-23 20:56

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20220123_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_added',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ اضافه شدن'),
        ),
    ]
