# Generated by Django 3.2 on 2022-01-23 20:18

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ پیوستن'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='اخرین  ورود'),
        ),
    ]
